plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - CHANGELOG.md
remote_theme: https://github.com/d-dilsiz/minimal/_layouts/default.html
logo: /pictures/banner2.png
show_downloads: true
